#%RAML 1.0
title: sps-swapi-sapi-svc
types:
  people: !include /types/responses/get_people.raml
/v1:
  /peoples:
    get:
      headers:
        page:
          type: number
          required: false
      queryParameters:
        gender: 
          type: string
          required: false
          example: female
      description: 
      responses:
        200:
          body:
            application/csv:
              type: people
        400:
          description: no found